In [1]:
# HEURISTIC
import pandas as ps
import numpy as np
import datetime
import time
MAX = 99999999999999
data = ps.read_csv("11citytsp.csv", header=None).values
for i in range(data.shape[0]):
    for j in range(data.shape[1]):
        if(i==j):
            data[i][j] = MAX
print(data)

[[99999999999999            633            257             91
             412            150             80            134
             259            505            353]
 [           633 99999999999999            390            661
             227            488            572            530
             555            289            282]
 [           257            390 99999999999999            228
             169            112            196            154
             372            262            110]
 [            91            661            228 99999999999999
             383            120             77            105
             175            476            324]
 [           412            227            169            383
  99999999999999            267            351            309
             338            196             61]
 [           150            488            112            120
             267 99999999999999             63             34
             264

In [2]:
def get_path(start, data, path, length):
    min_dist = MAX
    min_indx = -1
    k = 0
    while(k < data.shape[0]):
        if(data[start][k] < min_dist):
            min_dist = data[start][k]
            min_indx = k
        k+=1
    if min_dist == MAX:
        path.append(path[0])
        length += data[path[-1]][path[-2]]
        return path, length
    else:
        length += min_dist
        path.append(min_indx)
        for i in range(data.shape[0]):
            data[i][start] = MAX
        return get_path(min_indx, data, path, length)

In [3]:
s = datetime.datetime.now()
bPath = []
bLength = MAX
for i in range(data.shape[0]):
    path, length = get_path(i, data.copy(), [i], 0)
    if length < bLength:
        bLength = length
        bPath = path
e = datetime.datetime.now()
print(bPath, bLength, (e-s).total_seconds()*1000)

[0, 6, 7, 5, 2, 10, 4, 9, 1, 8, 3, 0] 1732 1.211


In [4]:
# BRUTFORCE
import pandas as pd
import numpy as np
import time
from itertools import permutations
mat = pd.read_csv("6citytsp.csv", header=None).values
print(mat)
print(mat.shape[0])

[[  0  64 378 519 434 200]
 [ 64   0 318 455 375 164]
 [378 318   0 170 265 344]
 [519 455 170   0 223 428]
 [434 375 265 223   0 273]
 [200 164 344 428 273   0]]
6


In [5]:
s = time.process_time()
citynames = list(range(mat.shape[0]))
per = permutations(citynames)
btl = np.inf
bt = None
for tour in per:
    tl = 0
    for i in range(len(tour)-1):
        tl += mat[tour[i], tour[i+1]]
    tl += mat[tour[i+1], tour[0]]
    if tl < btl:
        btl = tl
        bt = list(tour)
e = time.process_time()
print(f"Time : {(e-s)} seconds.")
print("Best Tour : ", bt)
print("Best length : ", btl)

Time : 0.0 seconds.
Best Tour :  [0, 1, 2, 3, 4, 5]
Best length :  1248


In [6]:

# BRUTFORCE WITH STARTING POINT
start = int(input("Enter start city : " ))
s = time.process_time()
citynames = list(range(mat.shape[0]))
citynames.remove(start)
per = permutations(citynames)
btl = np.inf
bt = None
for tour in per:
    tl = 0
    for i in range(len(tour)-1):
        tl += mat[tour[i], tour[i+1]]
    tl += mat[tour[i+1], start]
    tl += mat[start, tour[0]]
    if tl < btl:
        btl = tl
        bt = list(tour)
bt.insert(0, start)
e = time.process_time()
print(f"Time : {(e-s)} seconds.")
print("Best Tour : ", bt)
print("Best length : ", btl)

Enter start city : 4
Time : 0.0 seconds.
Best Tour :  [4, 3, 2, 1, 0, 5]
Best length :  1248
